name: crafter-rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - cudatoolkit=11.8  # Adjust based on your CUDA version
  - pip
  - numpy
  - matplotlib
  - jupyter
  - ipython
  - pip:
      - crafter>=1.8.0
      - gymnasium>=0.29.0
      - stable-baselines3>=2.0.0
      - tensorboard>=2.13.0
      - wandb>=0.15.0
      - opencv-python>=4.8.0
      - pyyaml>=6.0
      - tqdm>=4.65.0
      - pandas>=2.0.0
      - seaborn>=0.12.0
      - scikit-learn>=1.3.0
      - pytest>=7.4.0